services:
  mongodb:
    image: mongo:4.4.29
    container_name: audiobook-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --wiredTigerCacheSizeGB 0.25
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: