spring:
  application:
    name: audiobook-library
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/audiobook_db?authSource=admin
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

file:
  # Use barras normais / mesmo no Windows, o Java entende e evita erros de escape
  base-dir: "C:/projetos/audiobook-library/src/main/resources/"
  downloads-dir: "${file.base-dir}downloads"
  images-dir: "${file.base-dir}images"

# java -jar audiobook-library.jar --file.base-dir=/var/lib/audiobook-library/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true