server:
  servlet:
    context-path: /audiobook-library

spring:
  application:
    name: audiobook-library
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/audiobook_db?authSource=admin&connectTimeoutMS=10000&socketTimeoutMS=60000
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000 # 1 mes em ms


file:
  # Use barras normais / mesmo no Windows, o Java entende e evita erros de escape
  base-dir: "C:/projetos/audiobook-library/src/main/resources/"
  downloads-dir: "${file.base-dir}downloads"
  images-dir: "${file.base-dir}images"

# java -jar audiobook-library.jar --file.base-dir=/var/lib/audiobook-library/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true